import "server-only";

export function buildRegistrationInvite({ recipientName, invitationUrl }: { recipientName?: string; invitationUrl: string }) {
    const subject = "Héjja-Farm – meghívó csirke előrendeléshez";
    const escape = (value: string) => value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#039;");
    const greeting = recipientName?.trim() ? `Kedves ${recipientName.trim()}!` : "Kedves Vásárlónk!";
    const url = escape(invitationUrl);
    const text = [
        greeting, "", "Mostantól a korábbi telefonos egyeztetés helyett a Héjja-Farm online felületén adhatod le csirke-előrendelésedet.", "",
        "Kiválaszthatod az átvételi napot, rendeléseidet pedig később is megtekintheted, módosíthatod vagy törölheted.", "",
        "A rendelésekről és azok változásairól e-mailes visszaigazolást küldünk, az átvétel előtt pedig emlékeztetőt is kapsz.", "",
        "A regisztráció megkezdéséhez kattints az alábbi gombra.", invitationUrl, "",
        "Az adatok megadása után e-mailben küldünk egy megerősítő linket, amellyel véglegesítheted a regisztrációt.", "",
        "Kérdés esetén írj a hejja-farm-csirke@gmail.com címre.", "", "Üdvözlettel:", "Héjja-Farm",
    ].join("\n");
    const html = `<!doctype html>
<html lang="hu"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${subject}</title></head>
<body style="margin:0;padding:0;background:#f4f7f5;color:#374151;"><div style="display:none;max-height:0;overflow:hidden;opacity:0;">Meghívó a Héjja-Farm csirke-előrendelő oldalára.</div>
<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%;background:#f4f7f5;"><tr><td align="center" style="padding:28px 12px;"><table role="presentation" width="680" cellspacing="0" cellpadding="0" border="0" style="width:100%;max-width:680px;background:#fff;border-radius:14px;overflow:hidden;box-shadow:0 3px 14px rgba(17,24,39,.07);">
<tr><td align="center" style="padding:28px 34px 24px;background:#f1fbf6;border-bottom:1px solid #dcefe4;font-family:Arial,Helvetica,sans-serif;"><img src="https://hejja-farm.hu/images/logo2.png" width="64" height="64" alt="Héjja Ökofarm" style="display:block;width:64px;height:64px;border:0;"><div style="padding-top:12px;font-size:14px;line-height:22px;font-weight:700;color:#374151;">Héjja Ökofarm</div></td></tr>
<tr><td style="padding:30px 34px 32px;font-family:Arial,Helvetica,sans-serif;font-size:14px;line-height:22px;"><p style="margin:0 0 20px;color:#4b5563;">${escape(greeting)}</p><p style="margin:0 0 22px;color:#4b5563;">Mostantól a korábbi telefonos egyeztetés helyett a Héjja-Farm online felületén adhatod le csirke-előrendelésedet.</p><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="margin-bottom:14px;"><tr><td width="32" style="vertical-align:top;"><span style="display:inline-block;width:24px;height:24px;border-radius:50%;background:#e9f9f1;color:#218856;font-size:14px;line-height:24px;text-align:center;font-weight:700;">1</span></td><td style="padding-left:4px;color:#4b5563;">Kiválaszthatod az átvételi napot, rendeléseidet pedig később is megtekintheted, módosíthatod vagy törölheted.</td></tr></table><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="margin-bottom:20px;"><tr><td width="32" style="vertical-align:top;"><span style="display:inline-block;width:24px;height:24px;border-radius:50%;background:#e9f9f1;color:#218856;font-size:14px;line-height:24px;text-align:center;font-weight:700;">2</span></td><td style="padding-left:4px;color:#4b5563;">A rendelésekről és azok változásairól e-mailes visszaigazolást küldünk, az átvétel előtt pedig emlékeztetőt is kapsz.</td></tr></table><p style="margin:0;color:#4b5563;">A regisztráció megkezdéséhez kattints az alábbi gombra.</p>
<div style="padding:24px 0;text-align:center;"><a href="${url}" target="_blank" style="display:inline-block;padding:13px 26px;border-radius:8px;background:#38b878;color:#fff;text-decoration:none;font-size:14px;line-height:22px;font-weight:700;">Regisztráció megkezdése</a></div><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="margin-bottom:18px;background:#f1fbf6;border-left:3px solid #46cc8d;border-radius:0 8px 8px 0;"><tr><td style="padding:15px 17px;font-size:14px;line-height:22px;color:#4b5563;">Az adatok megadása után e-mailben küldünk egy megerősítő linket, amellyel véglegesítheted a regisztrációt.</td></tr></table><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="background:#fff9e9;border-left:3px solid #e8b931;border-radius:0 8px 8px 0;"><tr><td style="padding:15px 17px;font-size:14px;line-height:22px;color:#4b5563;"><strong style="color:#8a6514;">Nem te kezdeményezted?</strong><br>Ha nem te regisztráltál, nincs további teendőd, ezt az e-mailt figyelmen kívül hagyhatod.</td></tr></table><p style="margin:28px 0 0;padding-top:18px;border-top:1px solid #e5e7eb;font-size:14px;line-height:22px;color:#6b7280;font-style:italic;">&#9993;&nbsp; Ez egy automatikus e-mail, kérjük, ne válaszolj rá.<br>Kérdés vagy probléma esetén írj a <a href="mailto:hejja-farm-csirke@gmail.com" style="color:#218856;font-weight:700;text-decoration:none;">hejja-farm-csirke@gmail.com</a> címre.</p><p style="margin:24px 0 0;font-size:14px;line-height:22px;color:#6b7280;">Üdvözlettel:<br><strong style="color:#4b5563;">Héjja-Farm</strong></p></td></tr>
</table></td></tr></table></body></html>`;
    return { subject, text, html };
}
